### ISSUE TITLE
Greenisland doesn't compile with qt 5.6 due to linker errors

### ISSUE THREAD

**Issue by n3rdopolis** [greenisland/greenisland#155]
I am getting the following errors trying to compile greenisland against qt 5.6

[ 51%] Building CXX object tests/auto/platform/CMakeFiles/tst_logind.dir/tst_logind_automoc.cpp.o
Scanning dependencies of target tst_libinput
[ 52%] Building CXX object tests/manual/platform/CMakeFiles/tst_libinput.dir/tst_libinput.cpp.o
[ 52%] Linking CXX shared library libGreenIslandCompositor.so
[ 53%] Linking CXX executable tst_logind
[ 53%] Built target tst_logind
[ 53%] Building CXX object tests/manual/platform/CMakeFiles/tst_libinput.dir/tst_libinput_automoc.cpp.o
CMakeFiles/GreenIslandCompositor.dir/wayland_wrapper/qwlcompositor.cpp.o: In function `QtWayland::WindowSystemEventHandler::sendEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)':
qwlcompositor.cpp:(.text._ZN9QtWayland24WindowSystemEventHandler9sendEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE[_ZN9QtWayland24WindowSystemEventHandler9sendEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE]+0x8a): undefined reference to `QWaylandXkb::modifiers(xkb_state*)'
qwlcompositor.cpp:(.text._ZN9QtWayland24WindowSystemEventHandler9sendEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE[_ZN9QtWayland24WindowSystemEventHandler9sendEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE]+0x10f): undefined reference to `QWaylandXkb::keysymToQtKey(unsigned int, QFlags<Qt::KeyboardModifier>&, QString const&)'
collect2: error: ld returned 1 exit status
src/waylandcompositor/CMakeFiles/GreenIslandCompositor.dir/build.make:1989: recipe for target 'src/waylandcompositor/libGreenIslandCompositor.so.0.6.92' failed
make[2]: *** [src/waylandcompositor/libGreenIslandCompositor.so.0.6.92] Error 1
CMakeFiles/Makefile2:1504: recipe for target 'src/waylandcompositor/CMakeFiles/GreenIslandCompositor.dir/all' failed
make[1]: *** [src/waylandcompositor/CMakeFiles/GreenIslandCompositor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 53%] Building CXX object tests/auto/platform/CMakeFiles/tst_udev.dir/tst_udev_automoc.cpp.o
[ 53%] Linking CXX executable tst_libinput
[ 54%] Linking CXX executable tst_udev
[ 54%] Built target tst_libinput
[ 54%] Built target tst_udev
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
PackageCompileSource finished in 207 seconds
